### ISSUE TITLE
Module inutilisable vvt 0.8.6

### ISSUE THREAD

**Issue by 0Croizer** [ZigmundKreud/coc#15]
Les CARAC. ne s'affiche pas
erreur
TypeError: Cannot convert undefined or null to object

**Comment by Qaw** [comment]
Oui c'est normal cette version n'est pas compatible avec Foundry 0.8.x

**Comment by MJFredIK** [comment]
Bonjour, Est ce qu'une nouvelle version est en cours ou seul celui de  Foundry 0.7.x restera la seul version ?

**Comment by Qaw** [comment]
Une version compatible est en cours mais le développement reprendra en août.
Une refonte complète de COC est en réflexion mais sans date de livraison .
