### ISSUE TITLE
Drag n drop depuis la fiche de Voie

### ISSUE THREAD

**Issue by Antwan37** [ZigmundKreud/coc#23]
![image](https://user-images.githubusercontent.com/70380738/134248269-90f68432-3b2e-49ce-a459-c0fc24efd4e5.png)
Salut,
Le drag n Drop d'une CAPACITE n'est pas possible depuis la fiche de la VOIE vers la fiche du PNJ **(type rencontre)**
Pourtant on peut dropper depuis la fiche du PNJ vers la fiche de la voie.

Est-il possible d'avoir cette feature afin de gagner du temps sur la recherche de chaque capacité ?

**Comment by Qaw** [comment]
C'est possible de rechercher une capacité depuis le compendium des capacités, puis de la droper sur la fiche.
