### ISSUE TITLE
Token Action HUD - Translation Error

### ISSUE THREAD

**Issue by Duschmolll** [ZigmundKreud/coc#24]
Bonjour, 

Lorsque nous avons l'interface en Anglais et un token selectionné avec une arme d'équipé, l'onglet des armes n'est pas traduite.

C'est affiché: Tokenactionhud.co.combat.

![image](https://user-images.githubusercontent.com/65500704/171471016-7901ecc1-dd18-4141-8cf8-85c1c7d6cf82.png)

Lorsque l'inferface est en français il n'y a pas de soucis.

De plus, si ça serait possible d'avoir les 'Attaques de rencontres' ainsi que les' capacités' des Encounter d'indiqué dans le Token Action HUD lorsqu'ils sont sélectionner ?

Hello, I've seen that with Token Action HUD, there is an error with the english translation. See the image abose, in the section for the equiped weapons.

Thanks and good luck for the dev.

Merci d'avance, et bon courage !
PS: (If there is a discord for COC dev, could you let me know, I would like to join)

**Comment by Qaw** [comment]
Il y a un canal Chroniques oubliées sur le discord La Fonderie : https://discord.com/channels/715943353409339425/724327168573964294

**Comment by Qaw** [comment]
J'ai envoyé une MR pour les clés manquantes, est-ce que tu peux dupliquer l'issue pour la partie des Rencontres ?

**Comment by Duschmolll** [comment]
Je pense pas que se soit une issue mais juste une fonction non-implémenté dans CoC. Ou juste moi qui ai mal fait les choses (je viens de commencer tout juste Foundry)

Par exemple dans ce Token de Rencontre, ses stats, attaques et capacités ne sont pas accessible depuis l'Action Token HUD.
![image](https://user-images.githubusercontent.com/65500704/171502774-bcc5e755-1445-4d68-8fde-f0af93d71768.png)

Merci pour le lien du discord, j'avais plus en tête un discord dédié à CO et pouvoir aider le developpement des system/modules.

**Comment by Qaw** [comment]
Issue c'est un terme générique, c'est pas forcément un bug
La c'est une évolution. Le support du module dans TA HUD n'est pas implémenté pour les rencontres
Et les devs du système sont sur la Fonderie, donc n'hésite pas à discuter là bas.
 C'est plus simple quand dans les commentaires Github 
😉

**Comment by Qaw** [comment]
Corrigé dans la version 2.2.17 de Token Action HUD
