### ISSUE TITLE
V10 - création d'effets

### ISSUE THREAD

**Issue by DarKDinDoN** [ZigmundKreud/coc#30]
Hello,

Sur la V10, lorsqu'on tente de créer un effet sur une FdP, on a l'erreur suivante :
![image](https://user-images.githubusercontent.com/1687854/179264404-bf6be35e-fb6c-429c-92ac-b81662f08648.png)

**Comment by Thoru-dev** [comment]
Le problème existe aussi sur la v9 que j'utilise en ce moment.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/106152282/196194785-26f243a4-6c1b-474e-898e-32716cd55e08.png">
