### ISSUE TITLE
Doublons dans les Voies

### ISSUE THREAD

**Issue by Obiatn** [ZigmundKreud/coc#4]
- Voie de la Survie apparait 2x (l'une d'entre a une Capacité Survivant avec une icône de fantôme / l'autre non)

- Voie de la Psychologie 2x (l'une avec les Capacités Analyse Personnelle et Aide Psychologique en 2 et 3 / l'autre avec Mental d'Acier et Intervention Psychologique)

- Voie du Danger 2x (l'une avec la Capacité Même pas Peur avec une icône de fantôme / l'autre non)

- Voie du Démon 2x (vides pour l'instant toutes les 2)

**Comment by ZigmundKreud** [comment]
C'est pas un bug il s'agit de variantes des voies de base pour le setting épouvante.
